"$schema" = 'https://starship.rs/config-schema.json'

right_format = """"""

continuation_prompt = '▶▶ '

format = """
[┌────────────{$time}─────────────────>](bold cyan)
[│](bold cyan)${custom.languages}$c${custom.makefile}
[│](bold cyan) [user: ](bold green)$username(white)
[│](bold cyan) [directory: ](bold green)$directory
[│](bold cyan)${custom.git} ${git_branch}${git_status}
[└─](bold cyan)$os$character
"""

add_newline = false

[custom.git]
detect_folders = ['.git']
format = "[ git:](bold green)"

[custom.languages]
detect_files = ['Makefile']
detect_extensions = ['c']
format = "[ languages:](bold green)"

[custom.makefile]
detect_files = ['Makefile']
format = "[$symbol]($style)"
symbol = " "
style = "bold white"

[time]
disabled = false
format="[$time]($style)"
time_format = '%T'
style = "bold white"

[c]
format = "[$symbol]($style)"
symbol = " "
detect_extensions = ['c', 'h']
style = "bold white"

[character]
success_symbol = '[ ↣](bold green)'
error_symbol = '[ ↣](bold red)'

[username]
style_user = 'bold white'
disabled = false
show_always = true
format = '[$user]($style)'

[directory]
style = 'bold white'

[os]
disabled = false
style = "bold white"

[os.symbols]
Windows = "󰍲"
Ubuntu = ""
SUSE = ""
Raspbian = ""
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[git_branch]
format = "[$symbol$branch]($style)"
style="bold white"

[git_status]
format = "[ | ](bold white) [$renamed$typechanged$untracked$behind$ahead$modified$up_to_date]($style)"
stashed = '[](bold yellow)'
untracked = '[󰤔](bold red)'
behind = '[ ](bold red)'
diverged = '[](bold yellow)'
renamed = '[](bold yellow)'
ahead = '[ ](bold red)'
deleted = '[](bold red)'
modified = '[](bold yellow)'
typechanged = '[](bold yellow)'
staged = '[󰥔](bold yellow)'
up_to_date = '[](bold green)'
